// Generated by CoffeeScript 1.6.3
(function() {
  var Backend, backend, homePage, parse, readFileSync, whois;

  parse = require('url').parse;

  whois = require('node-whois');

  readFileSync = require('fs').readFileSync;

  homePage = readFileSync('./views/home.html');

  Backend = require('backend').Backend;

  backend = new Backend('ec2-54-226-131-21.compute-1.amazonaws.com');

  backend.addHandler().Id('43q.name:home').Match({
    uri: {
      hostname: '53q.name',
      pathname: '/'
    }
  }).Handler(function(req, res) {
    return res(homePage.toString(), 200, {
      'Content-Type': 'text/html'
    });
  });

  backend.addHandler().Id('43q.name:q').Match({
    uri: {
      hostname: '53q.name',
      pathname: '/q'
    }
  }).Handler(function(req, res) {
    return whois.lookup(req.uri.query.domain, function(err, data) {
      console.log(data);
      return res(JSON.stringify({
        result: data
      }), 200, {
        'Content-Tye': 'application/json'
      });
    });
  });

  backend.register();

}).call(this);
